version: "3.7"
services:
  condor:
    image: dodasts/mini-htc:v0

    environment:
      IAM_SERVER: 'https://iam.cloud.infn.it/'
      IAM_SCOPES: 'openid profile email offline_access wlcg wlcg.groups'

    volumes:
      - ${PWD}/submituser:/home/submituser/
      - ${PWD}/conf/condor_config.local:/etc/condor/condor_config.local
      - ${PWD}/conf/gettoken.sh:/usr/bin/gettoken.sh

    command: /bin/sh -c "/home/submituser/start_script.sh && tail -f /dev/null"
