version: "3.7"
services:
  condor:
    image: dodasts/mini-htc:v0
    container_name: mycondor
    environment:
      OIDC_AGENT: "mycondor-wlcg"
      REFRESH_TOKEN: ${REFRESH_TOKEN}
      IAM_CLIENT_SECRET: ${IAM_CLIENT_SECRET}
      IAM_CLIENT_ID: ${IAM_CLIENT_ID}
      IAM_SERVER: 'https://iam.cloud.infn.it'
      IAM_SCOPES: 'openid profile email offline_access wlcg wlcg.groups'

    volumes:
      - ${PWD}/private:/private/
      - ${PWD}/conf/condor_config.local:/etc/condor/condor_config.local
      - ${PWD}/conf/gettoken.sh:/usr/bin/gettoken
      - ${PWD}/conf/start_script.sh:/start_script.sh

    command: /bin/sh -c "/start_script.sh && tail -f /dev/null"
